<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Configuration Condition="'$(Configuration)' == ''">Release</Configuration>
    <Product>CursorCapturer</Product>
    <AssemblyName>CursorCapturer</AssemblyName>
    <Version>1.0.1</Version>
    <Company>Gaven</Company>
    <Description>Records cursor position per video frame</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
    <None Update="CursorCapturer.anm2" CopyToOutputDirectory="PreserveNewest" />
    <None Update="README.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
